version: '3.8'

services:
#  redis:
#    container_name: aigdscmeet-redis
#    build:
#      context: ./Redis
#      dockerfile: Dockerfile
#    ports:
#      - "6080:6080"
#    networks:
#      - mynetwork
#    volumes:
#      - ./redis.conf:/etc/redis/redis.conf

  rebase:
    container_name: aigdscmeet-socketio-1
    build:
      context: ./Rebase
      dockerfile: Dockerfile
    ports:
      - "5300:5300"
    env_file:
      - Rebase/PATH.env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
